# Generated by Django 5.0.5 on 2024-05-15 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0002_choice_feedback_choice_is_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
